### PR TITLE
Composer 2

### PR DESCRIPTION
**Pull request by ReplicaObscura**

### CODE REVIEW

**Comment by nicoschi** [comment]
Hi there, 
without this merge and a new release we can't no longer use this library with composer 2. 
Or is there any workaround which allow us continuing to use this library without a fork?

**Comment by theodorosploumis** [comment]
Waiting for this too, any updates? Thank you.

**Comment by philwolstenholme** [comment]
If this work is ready it'd be great if it could be merged and a new release made for Composer 2.

But for now we can tell Composer to install the plugin from this branch to avoid needing to wait for a release:

```
        "topfloor/composer-cleanup-vcs-dirs": "dev-composer-2",
```

**Comment by nicoschi** [comment]
I didn't know I can download a different branch than master. Thanks @philwolstenholme

**Comment by ReplicaObscura** [comment]
Version 1.1.0 should finally have these changes in. Sorry for the long delay!

**Comment by JohnAlbin** [comment]
Now that 1.1.0 has been released (thanks!), what's the preferred namespace? Should we use "TopFloorTech/composer-cleanup-vcs-dirs" or "VolantisDev/composer-cleanup-vcs-dirs"?

VolantisDev has a [1.1.0 named release in GitHub](https://github.com/VolantisDev/composer-cleanup-vcs-dirs/releases), but both namespaces work with composer when requiring 1.1.0.

**Pull request merged**
